# Generated by Django 3.2.8 on 2021-12-02 19:51

from django.db import migrations, models
import django.utils.timezone
import userupload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('tmdbId', models.PositiveIntegerField()),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=userupload.models.upload_to, verbose_name='Image')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
