# Generated by Django 3.2.8 on 2021-12-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userupload', '0002_post_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
