# Generated by Django 3.2.8 on 2021-10-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simrec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('vote_count', models.PositiveIntegerField()),
                ('vote_average', models.FloatField()),
                ('weighted_score', models.FloatField()),
            ],
        ),
    ]
